name: slide
description: A creative spin on the classic sliding puzzle game.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_portal: ^0.4.0
  google_fonts: ^2.3.1
  material_design_icons_flutter: ^5.0.6595
  url_strategy: ^0.2.0
  yaml: ^3.1.0
  archive: ^3.1.11
  flex_color_scheme: ^4.2.0
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/levels.yaml
